### ISSUE TITLE
package.json doenst have react-copy-to-clipboard

### ISSUE THREAD

**Issue by radjivC** [Cloudhuset/Zendesk-React-App-Boilerplate#1]

**Comment by Herlevsen** [comment]
I don't think it's used anymore so i think we can remove it

**Comment by radjivC** [comment]
Yes, can its not use 

https://github.com/Cloudhuset/Zendesk-React-App-Boilerplate/blob/master/src/containers/PageOne/index.js

**Comment by Herlevsen** [comment]
I have removed the reference to CopyToClipboard
