### ISSUE TITLE
Sinatra doesn’t know this ditty.

### ISSUE THREAD

**Issue by OlegGulevskyy** [Cloudhuset/Zendesk-React-App-Boilerplate#14]
When trying the boilerplate, it returns this in in the iframe:
Try this:

```
# in Library/Ruby/Gems/2.6.0/gems/zendesk_apps_tools-3.7.1/lib/zendesk_apps_tools/server.rb
class ZendeskAppsTools::Server
  get '/index.html' do
    "Hello World"
  end
end

```

What is the reason for this? I saw a duplicate issue but adding this to server.rb does not change a thing for me.

**Comment by kevinNgws** [comment]
Hi @OlegGulevskyy, i have the same issue as well. How do you go about resolving it?

**Comment by kevinNgws** [comment]
@OlegGulevskyy, i managed to get it to work by following the steps here: https://github.com/Cloudhuset/Zendesk-React-App-Boilerplate/issues/8
