### ISSUE TITLE
Indent as error

### ISSUE THREAD

**Issue by superandrew** [Cloudhuset/Zendesk-React-App-Boilerplate#21]
in .eslintrc, `"indent": ["error", 2],` makes impossible to work with vs code and prettier. When prettier saves in some cases the production  build can't be built.

![CleanShot 2020-10-29 at 17 15 43](https://user-images.githubusercontent.com/71364/97601376-63b91080-1a0a-11eb-944c-4e224f8d12c5.png)

 Is this intended?

**Comment by Herlevsen** [comment]
We do not include prettier in this repository, so it must be your own global prettier installation and configuration that conflicts.

You can:
1. Turn off your own global prettier in your editor, or
2. Add your own .prettierrc in the root of the project and configure it for 2 spaces, or
3. Change the .eslintrc indent rule

**Comment by superandrew** [comment]
Yes, @Herlevsen that's what I did. I just fired up a standard VS Code and worked from there so I thought it might be useful for the community who works on this project to know. On my side I already solved as you suggested with 3. I am just saying that as a rule for a compilation error for production might be a little bit too harsh, maybe?

Anyway if this is known and fine for the project, please feel free to close the issue, and thank you for your advices.

**Comment by Herlevsen** [comment]
I see. I'll leave it as it is for now, but if we receive more feedback about it, we might make it a warning instead :-)
