### ISSUE TITLE
Modal Support

### ISSUE THREAD

**Issue by DKBoston15** [Cloudhuset/Zendesk-React-App-Boilerplate#25]
The boilerplate is incredibly useful. Could you show an example of how to implement a modal with this boilerplate?

I tried to implement it with the following structure.
<img width="239" alt="Screen Shot 2021-05-05 at 5 39 33 PM" src="https://user-images.githubusercontent.com/46634008/117226146-dbf0fc00-adc8-11eb-9dd1-c57b8e1467ff.png">

And with the following code being called from a button on index.js, but I get the error below in the image:
`
  const myFunction = () => {
    return zafClient.invoke("instances.create", {
      location: "modal",
      url: "assets/modals/test.html",
      size: {
        width: "585px",
        height: "525px",
      },
    });
  };`

<img width="762" alt="Screen Shot 2021-05-05 at 5 42 40 PM" src="https://user-images.githubusercontent.com/46634008/117226337-4bff8200-adc9-11eb-9e33-43540557271f.png">

**Comment by Herlevsen** [comment]
Hi @DKBoston15 
That does not look like something specific to this boilerplate. Looks like Sinatra can not find the modal file. Have you tried moving the file out to the assets folder? I'm not sure if sub directories are supported in Zendesk apps  :-)

**Comment by neiljensen** [comment]
The times that I ran into that error, were because I was running the zat server from the wrong directory. I don't know if that will help or not, but that is when I saw that error.
