### ISSUE TITLE
Jsx is not reconize by webpack

### ISSUE THREAD

**Issue by radjivF** [Cloudhuset/Zendesk-React-App-Boilerplate#3]
I have try to fix it and it didnt work :/, any idea?

**Comment by Herlevsen** [comment]
What do you mean by "it's not recognized"? Does it not compile? What output do you get?

**Comment by radjivC** [comment]
cannot find the file  when you require them

**Comment by Herlevsen** [comment]
Do you mean that it does not resolve files with ".jsx" extension? You can add that to the webpack configuration. It does parse jsx in .js files and you shoud be able to explicitly require a ".jsx" file :-)

**Comment by radjivC** [comment]
if i do a ```import Component from 'component.jsx' ```
The builder doesnt reconize it. Jsx is already in the preset. Do you have any idea where is that come from?

**Comment by Herlevsen** [comment]
It's just the webpack configuration that isn't setup to use the babel-loader for .tsx files. We just need to change the loader test.

**Comment by radjivC** [comment]
something like that ? 

```        
test: /\.(js|jsx)$/,
```

**Comment by Herlevsen** [comment]
Yes exactly like that :-) I have added it to the config file. I've also added it to the extensions array, so it resolves .jsx files with import `Component from 'Component'`
