### ISSUE TITLE
npm install issue with node-sass

### ISSUE THREAD

**Issue by thisisjagan** [Cloudhuset/Zendesk-React-App-Boilerplate#34]
Hi Team,

I am using Windows 10 with WSL enabled. I am running Zat in WSL Ubuntu and I am trying to clone and run this boilerplate app in the same environment.

After cloning the repo, if I try npm install or yarn install, the installation stops/terminates at the node-sass installation. 

Could you please help? I tried to install the node-sass separately without specifying the version. Installation works, but I get an error in the console that the version is incorrect. When installing the specific version in package.json, I get the same error.

node version: 8.1.3
yarn version: 1.22.15
Log file: [log.txt](https://github.com/Cloudhuset/Zendesk-React-App-Boilerplate/files/7588651/log.txt)

**Comment by Herlevsen** [comment]
Hi @thisisjagan.

Your node version is outdated. Try upgrading it.

If you install nvm (node version manager), you can have multiple version of node installed at once, and switch between them easily

**Comment by thisisjagan** [comment]
Sorry, that was my npm version. My node version is currently: v16.6.1 and npm is 8.1.3

**Comment by Herlevsen** [comment]
Ok. Try downgrading your node version to 10.x or 12.x instead :-)

**Comment by thisisjagan** [comment]
Thank you so much for your help. I am able to run the app now.
