### ISSUE TITLE
was wondering how to handle Client.on(ticket.updated)

### ISSUE THREAD

**Issue by miloshakes** [Cloudhuset/Zendesk-React-App-Boilerplate#47]
honestly just dont know where to place it in a react application without calling it multiple times.
its problematic in a sense that if i put it in the general use effect it wont be able to access any of the states when they are updated

**Comment by Herlevsen** [comment]
Hi @miloshakes,

That is an architectural question, unrelated to this boilerplate. There isn't a single answer for this.

You can add a useEffect in the topmost component, that needs access to the data from the zaf client, and then use setState to give your component access to the data. And then you can either manually pass the data to you child components, or alternatively use the context api if it's global state.

If you need more help, I will advise you to make a post in the Zendesk community.
