### ISSUE TITLE
Update to use ZCLI

### ISSUE THREAD

**Issue by buheryfi** [Cloudhuset/Zendesk-React-App-Boilerplate#48]
Should this be updated to use ZCLI rather than ZAT?

**Comment by Herlevsen** [comment]
Hi @buheryfi,

Feel free to submit a PR, replacing ZAT with ZCLI 🙂

**Comment by kaia-in-heaven** [comment]
I just submitted a PR for this - [https://github.com/Cloudhuset/Zendesk-React-App-Boilerplate/pull/49](https://github.com/Cloudhuset/Zendesk-React-App-Boilerplate/pull/49)
