### ISSUE TITLE
Development process

### ISSUE THREAD

**Issue by Chett23** [Cloudhuset/Zendesk-React-App-Boilerplate#8]
Hi, Thank you so much for the public boilerplate! I'm very new to the Zendesk App development world and I'm confused a little bit by the development process. in this example do i just use the yarn serve, or npm run serve, command to view my app in Zendesk or do i also need to start a node server to run the react code?

**Comment by OlegGulevskyy** [comment]
Hi @Chett23 ,
Have you figured this one out? I am asking myself the same question here :)

**Comment by Chett23** [comment]
HI @OlegGulevskyy,
Yes, I was able to work with this. I use npm to run the scripts. First, you need to run `npm install` to install all the dependencies, then you need to run ` npm run watch` to tell webpack to watch and build the react files. Then, while that is running you also need to run `npm run serve` this will start the at server. After that, you can then open your zendesk page in development mode to work. These commands are only like this if you are using this boilerplate set up. otherwise, the process is simple you will need to transpile/compile the react code into javascript build files then run the at server.

Let me know if you still have issues.

**Comment by OlegGulevskyy** [comment]
Wow, your explanation made it so easy, thank you a lot! Been struggling with it for few hours..

**Comment by Chett23** [comment]
Of course, I'm glad you got it!

**Comment by thisisjagan** [comment]
npm run watch doesnt work for me. It says its not configured in the config file and it is not actually. Can anyone help?

**Comment by Herlevsen** [comment]
@thisisjagan ```npm run dev``` 😊
